  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
#      - USER=username #optional
#      - PASS=password #optional
    volumes:
      - ./volumes/transmission/config:/config
      - ./downloads:/downloads
      - ./downloads/TransmissionWatchFolder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
